plugins:
  - rubocop-minitest

AllCops:
  NewCops: enable
  TargetRubyVersion: 4.0
  Exclude:
    - "coverage/**/*"
    - "vendor/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false
